
INSERT INTO ROUTINE
VALUES ('출근 전에', '목 스트레칭');

INSERT INTO ROUTINE
VALUES ('출근 전에', '커피 한 잔');

INSERT INTO ROUTINE
VALUES ('퇴근 후에', '책 1단원 읽기');

INSERT INTO ROUTINE
VALUES ('자기 전에', '반신욕 하기');

INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINE_ID)
VALUES (1, 1);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINE_ID)
VALUES (2, 1);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (3, 1);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (4, 1);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (5, 1);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (6, 1);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (7, 1);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (1, 2);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (3, 2);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (5, 2);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (2, 3);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (4, 3);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (6, 3);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (2, 4);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (3, 4);
INSERT INTO REPEATS(DAY_OF_ROUTINE, ROUTINES_ID)
VALUES (4, 4);